apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    matchLables: 
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
        - name: condo-admin
          image: 851725403957.dkr.ecr.us-east-1.amazonaws.com/demo:83788227f113a75e459c7346801a5cbf0e4cc618
          ports:
          - containerPort: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    name: demo
  ports:
    - protocol: tcp
      port: 3003
      targetport: 3003
      nodePort: 30003
  type: NodePort
