apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replica: 3
  selector:
    matchLables: 
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
        - name: condo-admin
          image: apurvbidkar/demo:latest
          ports:
          - containerPort: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    name: demo
  ports:
    - protocol: tcp
      port: 3003
      targetport: 3003
      nodePort: 30003
  type: NodePort
